# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fr', 'Français')], default='fr', max_length=6)),
                ('trans', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_kana', models.CharField(default='', max_length=30)),
                ('word_romaji', models.CharField(default='', max_length=40)),
                ('word_kanji', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='translation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.Word'),
        ),
    ]
