# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_kanji',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
